name: 'esmeta typecheck'

on: [pull_request]

jobs:
  esmeta-typecheck:
    name: 'esmeta typecheck'
    runs-on: ubuntu-22.04

    env:
      ESMETA_HOME: vendor/esmeta

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup SBT
        uses: sbt/setup-sbt@v1
      - name: download esmeta
        run: |
          mkdir -p "${ESMETA_HOME}"
          cd "${ESMETA_HOME}"
          git init
          git remote add origin https://github.com/es-meta/esmeta.git
          git fetch --depth 1 origin 2c53ff64f4d34fd4ff9ac6d4d90dfe09e2fe604e ;# v0.6.2
          git checkout FETCH_HEAD
      - name: build esmeta
        run: |
          cd "${ESMETA_HOME}"
          sbt assembly
      - name: link
        run: |
          rmdir "${ESMETA_HOME}"/ecma262 \
            && ln -s "$(pwd)" "${ESMETA_HOME}"/ecma262
      - name: typecheck
        run: '"${ESMETA_HOME}"/bin/esmeta tycheck -status -tycheck:log -tycheck:ignore=esmeta-ignore.json'

